runtime:      python27
api_version:  1
threadsafe:   true

# [START handlers]
handlers:
- url:        /css
  static_dir: templates/css

- url:        /js
  static_dir: templates/js

- url:        /.*
  script:     main.app
# [END handlers]

# [START libraries]
libraries:
- name: webapp2
  version: latest

- name: jinja2
  version: latest
# [END libraries]